services:
  db:
    image: postgres:15.2
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "5432:5432"
    networks:
      - financ
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: tgkaiser/financ:1.4.0
    restart: always
    env_file:
      - ./config/backend.env
    ports:
      - "8443:8080"
    networks:
      - financ
    depends_on:
      - db

  frontend:
    image: tgkaiser/financ-angular:1.3.3
    restart: always
    ports:
      - "3000:80"
    networks:
      - financ
    depends_on:
      - backend

volumes:
  db_data: {}

networks:
  financ:
